import type { DsrRecord } from "../../../../types/types";

export interface BannerColumn {
  key: string;
  label: string;
  groupLabel: string;
  minWidthClass: string;
  minWidthPx: number;
  align?: "left" | "right" | "center";
  color?: string; // Added color property for each column
}

// Define colors for each group
export const GROUP_COLORS: Record<
  string,
  { dark: string; light: string; text: string }
> = {
  ACTION: { dark: "bg-rose-600", light: "bg-rose-50", text: "text-rose-700" },
  STATUS: { dark: "bg-blue-600", light: "bg-blue-50", text: "text-blue-700" },
  BOOKING: {
    dark: "bg-fuchsia-600",
    light: "bg-fuchsia-50",
    text: "text-fuchsia-700",
  },
  CUSTOMER: {
    dark: "bg-emerald-600",
    light: "bg-emerald-50",
    text: "text-emerald-700",
  },
  TRIP: { dark: "bg-amber-500", light: "bg-amber-50", text: "text-amber-700" },
  ITINERARY: {
    dark: "bg-orange-600",
    light: "bg-orange-50",
    text: "text-orange-700",
  },
  "VEHICLE DETAILS": {
    dark: "bg-violet-600",
    light: "bg-violet-50",
    text: "text-violet-700",
  },
  "CUSTOMER QUOTE": {
    dark: "bg-cyan-600",
    light: "bg-cyan-50",
    text: "text-cyan-700",
  },
  "CUSTOMER PAYMENT": {
    dark: "bg-yellow-600",
    light: "bg-yellow-50",
    text: "text-yellow-700",
  },
  "VENDOR RATE & PAYMENT": {
    dark: "bg-indigo-600",
    light: "bg-indigo-50",
    text: "text-indigo-700",
  },
  "PAYMENT & BALANCE": {
    dark: "bg-teal-600",
    light: "bg-teal-50",
    text: "text-teal-700",
  },
  "TA MARGIN": {
    dark: "bg-green-600",
    light: "bg-green-50",
    text: "text-green-700",
  },
  "UC MARGIN": { dark: "bg-sky-600", light: "bg-sky-50", text: "text-sky-700" },
  REMARKS: { dark: "bg-pink-600", light: "bg-pink-50", text: "text-pink-700" },

  "ACCOUNTS REMARKS": {
    dark: "bg-yellow-600",
    light: "bg-yellow-50",
    text: "text-yellow-700",
  },
  "OPS FEEDBACK": {
    dark: "bg-lime-600",
    light: "bg-lime-50",
    text: "text-lime-700",
  },
};

export const DSR_TABLE_BANNER: BannerColumn[] = [
  {
    key: "actions",
    label: "ACTIONS",
    groupLabel: "ACTION",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
    align: "center",
  },
  {
    key: "dsr_date",
    label: "DSR DATE",
    groupLabel: "BOOKING",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
  },
  {
    key: "telesales",
    label: "TELE SALES",
    groupLabel: "BOOKING",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
  },
  // CUSTOMER GROUP
  {
    key: "fullName",
    label: "FULL NAME",
    groupLabel: "CUSTOMER",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  {
    key: "customerPhone",
    label: "PHONE",
    groupLabel: "CUSTOMER",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  {
    key: "companyName",
    label: "COMPANY NAME",
    groupLabel: "CUSTOMER",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  {
    key: "pickupDateTime",
    label: "PICKUP DATE",
    groupLabel: "TRIP",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  {
    key: "dropDateTime",
    label: "DROP DATE",
    groupLabel: "TRIP",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  {
    key: "days",
    label: "DAYS",
    groupLabel: "TRIP",
    minWidthClass: "min-w-[60px]",
    minWidthPx: 60,
  },
  {
    key: "pickupcity",
    label: "PICKUP CITY",
    groupLabel: "ITINERARY",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "pickupAddress",
    label: "PICKUP ADDRESS",
    groupLabel: "ITINERARY",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "itinerary",
    label: "ITINERARY",
    groupLabel: "ITINERARY",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "dropcity",
    label: "DROP CITY",
    groupLabel: "ITINERARY",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "dropAddress",
    label: "DROP ADDRESS",
    groupLabel: "ITINERARY",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "passengerTotal",
    label: "PAX",
    groupLabel: "ITINERARY",
    minWidthClass: "min-w-[60px]",
    minWidthPx: 60,
  },
  {
    key: "dsr_vehicles",
    label: "VEHICLES",
    groupLabel: "VEHICLE DETAILS",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
  },
  {
    key: "dsr_category",
    label: "CATEGORY",
    groupLabel: "VEHICLE DETAILS",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "veh_no",
    label: "VEHICLE NO",
    groupLabel: "VEHICLE DETAILS",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
  },
  {
    key: "driver",
    label: "DRIVER",
    groupLabel: "VEHICLE DETAILS",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
  },
  {
    key: "vendor_name",
    label: "VENDOR NAME",
    groupLabel: "VEHICLE DETAILS",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  // CUSTOMER QUOTE GROUP
  {
    key: "occasion",
    label: "OCCASION",
    groupLabel: "CUSTOMER QUOTE",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "customer_rate",
    label: "CUSTOMER RATE",
    groupLabel: "CUSTOMER QUOTE",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
    align: "right",
  },
  {
    key: "customer_toll",
    label: "CUSTOMER TOLL",
    groupLabel: "CUSTOMER QUOTE",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
    align: "right",
  },
  {
    key: "park_tax",
    label: "PARK TAX",
    groupLabel: "CUSTOMER QUOTE",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
    align: "right",
  },
  {
    key: "gst_amt",
    label: "GST AMOUNT",
    groupLabel: "CUSTOMER QUOTE",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
    align: "right",
  },
  {
    key: "total",
    label: "TOTAL",
    groupLabel: "CUSTOMER QUOTE",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
    align: "right",
  },
  {
    key: "booking_amount",
    label: "BOOKING AMOUNT",
    groupLabel: "CUSTOMER PAYMENT",
    minWidthClass: "min-w-[130px]",
    minWidthPx: 130,
    align: "right",
  },
  {
    key: "other_amount",
    label: "OTHER AMOUNT",
    groupLabel: "CUSTOMER PAYMENT",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
    align: "right",
  },
  {
    key: "bank_name",
    label: "BANK NAME",
    groupLabel: "CUSTOMER PAYMENT",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
  },
  {
    key: "amount_received",
    label: "AMOUNT RECEIVED",
    groupLabel: "CUSTOMER PAYMENT",
    minWidthClass: "min-w-[130px]",
    minWidthPx: 130,
    align: "right",
  },
  {
    key: "tds",
    label: "TDS",
    groupLabel: "CUSTOMER PAYMENT",
    minWidthClass: "min-w-[80px]",
    minWidthPx: 80,
    align: "right",
  },
  {
    key: "remaining_amount",
    label: "BALANCE AMOUNT",
    groupLabel: "CUSTOMER PAYMENT",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
    align: "right",
  },
  // VENDOR RATE & PAYMENT GROUP
  {
    key: "vendor_rate",
    label: "VENDOR RATE",
    groupLabel: "VENDOR RATE & PAYMENT",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
    align: "right",
  },
  {
    key: "vendor_toll",
    label: "VENDOR TOLL",
    groupLabel: "VENDOR RATE & PAYMENT",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
    align: "right",
  },
  {
    key: "vendor_park_tax",
    label: "VENDOR PARK TAX",
    groupLabel: "VENDOR RATE & PAYMENT",
    minWidthClass: "min-w-[130px]",
    minWidthPx: 130,
    align: "right",
  },
  {
    key: "customer_to_vendor",
    label: "CUST TO VENDOR",
    groupLabel: "VENDOR RATE & PAYMENT",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
    align: "right",
  },
  {
    key: "outstanding",
    label: "OUTSTANDING",
    groupLabel: "VENDOR RATE & PAYMENT",
    minWidthClass: "min-w-[110px]",
    minWidthPx: 110,
    align: "right",
  },
  {
    key: "payment_status",
    label: "PAYMENT STATUS",
    groupLabel: "VENDOR RATE & PAYMENT",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
  },
  {
    key: "balance_amount",
    label: "BALANCE",
    groupLabel: "VENDOR RATE & PAYMENT",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
    align: "right",
  },
  {
    key: "rate",
    label: "RATE",
    groupLabel: "TA MARGIN",
    minWidthClass: "min-w-[90px]",
    minWidthPx: 90,
    align: "right",
  },
  {
    key: "pay",
    label: "PAY",
    groupLabel: "TA MARGIN",
    minWidthClass: "min-w-[90px]",
    minWidthPx: 90,
    align: "right",
  },
  {
    key: "final_balance",
    label: "BALANCE",
    groupLabel: "TA MARGIN",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
    align: "right",
  },
  {
    key: "before_amt",
    label: "BEFORE",
    groupLabel: "UC MARGIN",
    minWidthClass: "min-w-[90px]",
    minWidthPx: 90,
    align: "right",
  },
  {
    key: "final_amt",
    label: "FINAL",
    groupLabel: "UC MARGIN",
    minWidthClass: "min-w-[90px]",
    minWidthPx: 90,
    align: "right",
  },
  {
    key: "gst",
    label: "GST",
    groupLabel: "UC MARGIN",
    minWidthClass: "min-w-[80px]",
    minWidthPx: 80,
    align: "right",
  },
  // REMARKS GROUP
  {
    key: "remarks_ts",
    label: "REMARKS TS",
    groupLabel: "REMARKS",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "remarks_mis",
    label: "REMARKS MIS",
    groupLabel: "REMARKS",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "remarksbyAccounts",
    label: "REMARKS BY ACCOUNTS",
    groupLabel: "ACCOUNTS REMARKS",
    minWidthClass: "min-w-[200px]",
    minWidthPx: 200,  },
  {
    key: "refundCancelShare",
    label: "REFUND/CANCEL SHARE",
    groupLabel: "ACCOUNTS REMARKS",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
   },
  {
    key: "feedbackByOfcs",
    label: "FEEDBACK BY OFCS",
    groupLabel: "OPS FEEDBACK",
    minWidthClass: "min-w-[200px]",
    minWidthPx: 200,
  },
  {
    key: "feedbackByCustomer",
    label: "FEEDBACK BY CUSTOMER",
    groupLabel: "OPS FEEDBACK",
    minWidthClass: "min-w-[200px]",
    minWidthPx: 200,
  },
  {
    key: "googleRating",
    label: "GOOGLE RATING",
    groupLabel: "OPS FEEDBACK",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
    align: "right",
  },
  {
    key: "mobileAppRating",
    label: "MOBILE APP RATING",
    groupLabel: "OPS FEEDBACK",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
    align: "right",
  },


];
